[IMP] l10n_eu_oss: tax groups are created and searched for the new taxes.
OCA/account-fiscal-rule pull request #217
Opened 2021-06-29 14:57 UTC by ValentinVinagre

tax groups are created and searched for the new taxes.

2021-06-29 15:09 UTC, pedrobaeza requested changes

2021-06-29 15:09 UTC, pedrobaeza commented on l10n_eu_oss/wizard/l10n_eu_oss_wizard.py
> +        return {"name": _("OSS VAT {}{}".format(rate, "%"))}
Use old replacing system (`%s`) and don't include in the translatable part the replacing itself:
```suggestion
        return {"name": _("OSS VAT %s%%") % rate}
```

2021-06-29 15:09 UTC, pedrobaeza commented on l10n_eu_oss/wizard/l10n_eu_oss_wizard.py
> +                            [("name", "=", _("OSS VAT {}{}".format(rate, "%")))]
Don't recreate the same group name, but call `self._prepare_tax_group_vals()["name"]`

2021-06-29 15:09 UTC, pedrobaeza commented on l10n_eu_oss/wizard/l10n_eu_oss_wizard.py
> +                            self._prepare_tax_vals(country, tax, rate, tax_group_id)
Don't change the arguments, but do the search/create inside the `_prepare_tax_vals` method IMO

2021-06-29 15:17 UTC, ValentinVinagre commented on l10n_eu_oss/wizard/l10n_eu_oss_wizard.py
> +                            self._prepare_tax_vals(country, tax, rate, tax_group_id)
I don't want to search / create the tax group in _prepare_tax_vals, I think this method should only add the fields to the dictionary, how do you see it?

2021-06-29 15:19 UTC, pedrobaeza commented on l10n_eu_oss/wizard/l10n_eu_oss_wizard.py
> +                            self._prepare_tax_vals(country, tax, rate, tax_group_id)
OK, I don't have right now an strong opinion on this. It's for being more self-contained.

2021-06-29 15:24 UTC, pedrobaeza commented on l10n_eu_oss/wizard/l10n_eu_oss_wizard.py
> +    def _prepare_tax_vals(self, country_id, tax_id, rate, tax_group_id):
Please don't use the suffix `_id` when you are passing a recordset.

```suggestion
    def _prepare_tax_vals(self, country_id, tax_id, rate, tax_group):
```

2021-06-29 15:24 UTC, pedrobaeza commented on l10n_eu_oss/wizard/l10n_eu_oss_wizard.py
> +                        tax_group_id = account_tax_group.search(
The same here about suffix.

2021-06-29 15:33 UTC, pedrobaeza approved these changes

2021-06-29 15:34 UTC, ValentinVinagre commented
thanks for review @pedrobaeza

2021-06-29 15:48 UTC, HaraldPanten approved these changes
Functional review 👍

2021-06-29 15:48 UTC, HaraldPanten commented
/ocabot merge patch

2021-06-29 16:19 UTC, merged

2021-06-30 08:54 UTC, Jortolsa commented
Today we will publish the PR with the migration of this module to 14.0.

2021-06-30 09:07 UTC, ValentinVinagre commented
> Today we will publish the PR with the migration of this module to 14.0.

Perfect @Jortolsa . Can you say it in https://github.com/OCA/account-fiscal-rule/issues/138 ? Thanks