Akretion/9.0 migration account fiscal rule
OCA/account-fiscal-rule pull request #45
Opened 2015-12-04 13:45 UTC by mbcosta

2015-12-04 17:04 UTC, danimaribeiro commented on account_fiscal_position_rule/views/account_fiscal_position_rule_view.xml
> +						<group string="General" colspan="4">
I suggest put the name attribute in the groups, in version 9 we can't use the string attribute to inherit views anymore.

2015-12-08 13:16 UTC, mbcosta commented on account_fiscal_position_rule/views/account_fiscal_position_rule_view.xml
> +						<group string="General" colspan="4">
Hi danimaribeiro, thanks for the feedbak, I add the attribute name

2015-12-08 15:26 UTC, rvalyi commented
@mbcosta: just a hint in case you don't know it: when you mention somebody in a comment, if you use @ like @danimaribeiro then you are sure that person will be notified. Else it depends a bit if the person is following the thread or not. The fix makes sense BTW.

2015-12-08 19:44 UTC, mbcosta commented
Thanks for the hint @rvalyi

2016-11-06 20:19 UTC, rvalyi commented on account_fiscal_position_rule/models/account_fiscal_position_rule.py
> +        result = self.fiscal_position_map(**kwargs)
better to write simply return self.fiscal_position_map(**kwargs)

2016-11-06 20:21 UTC, rvalyi requested changes

2016-11-06 20:21 UTC, rvalyi commented on account_fiscal_position_rule/models/account_fiscal_position_rule.py
> +        result = self.fiscal_position_map(**kwargs)
please use simply return self.fiscal_position_map(**kwargs)

2016-11-09 15:46 UTC, rvalyi commented
:+1:

2016-11-11 03:24 UTC, renatonlima commented
:+1:

2016-11-11 12:43 UTC, merged