11.0+ account fiscal position rule
OCA/account-fiscal-rule pull request #78
Opened 2018-02-05 12:52 UTC by hugosantosred

2018-03-08 17:44 UTC, mbcosta approved these changes

2018-05-25 10:01 UTC, Tonow-c2c requested changes
Check [https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0](https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0)

2018-05-25 10:01 UTC, Tonow-c2c commented on account_fiscal_position_rule/__init__.py
> +# -*- coding: utf-8 -*-
Remove This line [https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0#tasks-to-do-in-the-migration](https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0#tasks-to-do-in-the-migration)

2018-05-25 10:01 UTC, Tonow-c2c commented on account_fiscal_position_rule/__manifest__.py
> +# -*- coding: utf-8 -*-
Remove This line [https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0#tasks-to-do-in-the-migration](https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0#tasks-to-do-in-the-migration)

2018-05-25 10:01 UTC, Tonow-c2c commented on account_fiscal_position_rule/__manifest__.py
> +    'version': '10.0.1.0.0',
```'version': '11.0.1.0.0',```

2018-05-25 10:01 UTC, Tonow-c2c commented on account_fiscal_position_rule/models/account_fiscal_position_rule.py
> +# -*- coding: utf-8 -*-
Remove This line [https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0#tasks-to-do-in-the-migration](https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0#tasks-to-do-in-the-migration)

2018-05-25 10:01 UTC, Tonow-c2c commented on account_fiscal_position_rule/models/__init__.py
> +# -*- coding: utf-8 -*-
Remove This line [https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0#tasks-to-do-in-the-migration](https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0#tasks-to-do-in-the-migration)

2018-05-25 10:01 UTC, Tonow-c2c commented on account_fiscal_position_rule/models/account_invoice.py
> +# -*- coding: utf-8 -*-
Remove This line [https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0#tasks-to-do-in-the-migration](https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0#tasks-to-do-in-the-migration)

2018-05-25 10:01 UTC, Tonow-c2c commented on account_fiscal_position_rule/README.rst
> +.. image:: https://img.shields.io/badge/licence-AGPL--3-blue.svg
New Readme template in OCA:
* [https://github.com/OCA/maintainer-tools/blob/master/template/module/README.rst](https://github.com/OCA/maintainer-tools/blob/master/template/module/README.rst)
* [https://github.com/OCA/maintainer-tools/tree/master/template/module/readme](https://github.com/OCA/maintainer-tools/tree/master/template/module/readme)

2018-06-13 11:46 UTC, oleksandrpaziuk commented on account_fiscal_position_rule/security/account_fiscal_position_rule_security.xml
> +</odoo>
Please use indentation `4 spaces`

2018-06-13 11:46 UTC, oleksandrpaziuk commented on account_fiscal_position_rule/test/account_fiscal_position_rule_data.xml
> +
Please use indentation `4 spaces`

2018-06-13 11:47 UTC, oleksandrpaziuk commented on account_fiscal_position_rule/test/test_rules.yml
> +-
If possible migrate to py.test

2018-06-13 11:48 UTC, oleksandrpaziuk commented on account_fiscal_position_rule/views/account_fiscal_position_rule_view.xml
> +        <!-- Create Menu for Configuration and Generation Templates -->
Please use indentation `4 spaces`

2018-06-13 11:48 UTC, ghost reviewed
Some changes required

2018-06-13 11:52 UTC, leemannd reviewed
LGTM. Only one question for the moment

2018-06-13 11:52 UTC, leemannd commented on account_fiscal_position_rule/models/account_fiscal_position_rule.py
> +        # TODO fix me doesn't work multi template that have empty fiscal
I'm not fond of improvement requests while migrating a module, but what's the current status of this TODO?
If it's still needed, do you plan to work on it?

2021-12-05 12:26 UTC, closed without merging