11.0 mig account fiscal position rule purchase
OCA/account-fiscal-rule pull request #81
Opened 2018-05-25 08:57 UTC by Tonow-c2c

2018-06-11 08:24 UTC, leemannd requested changes
A few changes are required

2018-06-11 08:24 UTC, leemannd commented on account_fiscal_position_rule_purchase/__init__.py
> +# Copyright (C) 2009-TODAY Akretion <http://www.akretion.com>
Copyright can be dropped from `init.py` files

2018-06-11 08:24 UTC, leemannd commented on account_fiscal_position_rule_purchase/tests/test_account_fiscal_position_rule_purchase.py
> +from openerp.tests.common import TransactionCase
s/openerp/odoo/
Do you have runned tests locally? It doesn't fail with the import from `openerp` ?

2018-06-11 10:38 UTC, oleksandrpaziuk commented on account_fiscal_position_rule_purchase/security/ir.model.access.csv
> +
Is it is a reason to add an "empty" file?

2018-06-11 10:44 UTC, ghost approved these changes
LGTM

2018-06-11 10:46 UTC, ghost reviewed
Please fix oca_dependencies https://github.com/OCA/maintainer-quality-tools/blob/master/sample_files/oca_dependencies.txt

2018-06-14 07:03 UTC, Tonow-c2c commented
No need for this module cause he depend of any other OCA module

2020-04-16 09:04 UTC, dreispt commented
Superseded by #107

2020-04-16 09:04 UTC, closed without merging