Add new test to account fiscal position rule purchase
OCA/account-fiscal-rule pull request #82
Opened 2018-05-31 13:50 UTC by Tonow-c2c

2018-06-05 07:14 UTC, leemannd commented
@Tonow-c2c Is this still WIP, or ready for review?

2018-06-05 07:23 UTC, Tonow-c2c commented
@leemannd  now it's ok to review

2018-06-07 07:46 UTC, leemannd approved these changes
Not totally sure about it but LGTM

2018-06-07 07:50 UTC, p-tombez requested changes

2018-06-07 07:50 UTC, p-tombez commented on account_product_fiscal_classification/README.rst
> + * Sale Taxes: 20%;
Why change this ?

2018-06-07 07:50 UTC, p-tombez commented on account_fiscal_position_rule_purchase/models/purchase.py
> +        self.onchange_fiscal_position_map()
Not sure to understand why this method is needed

2018-06-07 07:50 UTC, p-tombez commented on account_fiscal_position_rule_purchase/tests/test_account_fiscal_position_rule_purchase.py
> +    def setUp(self):
You should use 
```
@staticmethod
def setUpClass(cls):
```
So it will not be called on every test

2018-06-07 13:27 UTC, Tonow-c2c commented on account_product_fiscal_classification/README.rst
> + * Sale Taxes: 20%;
To Travis depreciation

2018-06-07 13:31 UTC, Tonow-c2c commented on account_fiscal_position_rule_purchase/models/purchase.py
> +        self.onchange_fiscal_position_map()
Is to fix all test case https://github.com/OCA/account-fiscal-rule/pull/82/commits
[https://travis-ci.org/OCA/account-fiscal-rule/jobs/386189267#L1275](https://travis-ci.org/OCA/account-fiscal-rule/jobs/386189267#L1275)
[https://github.com/OCA/account-fiscal-rule/pull/82/files#diff-de10b22a6c1481d2ca990b1198f3600cR103](https://github.com/OCA/account-fiscal-rule/pull/82/files#diff-de10b22a6c1481d2ca990b1198f3600cR103)

2018-06-08 14:50 UTC, p-tombez requested changes

2018-06-08 14:50 UTC, p-tombez commented on account_fiscal_position_rule_purchase/tests/test_account_fiscal_position_rule_purchase.py
> +    @staticmethod
```@classmethod```
My bad :'(

2018-06-11 07:40 UTC, leemannd requested changes

2018-06-11 07:40 UTC, leemannd commented on account_fiscal_position_rule_purchase/tests/test_account_fiscal_position_rule_purchase.py
> +cls# -*- coding: utf-8 -*-
Can be removed

2018-07-26 11:47 UTC, legalsylvain approved these changes
A little suggestion.
Otherwise, LGTM.

:+1: Thanks.

2018-07-26 11:47 UTC, legalsylvain commented on account_product_fiscal_classification/models/account_product_fiscal_classification.py
> +            res = self.env['product.template'].search([
better write : 
```
            res = self.env['product.template'].with_context(active_test=False).search([
                ('fiscal_classification_id', '=', fiscal_classif.id)])
```

2018-07-26 12:05 UTC, leemannd approved these changes
Thanks

2018-07-26 12:09 UTC, legalsylvain commented
@p-tombez could you update your review ? 
regards.

2018-07-26 12:44 UTC, p-tombez approved these changes

2019-07-18 12:49 UTC, legalsylvain commented
This PR should be rebased i guess.

2019-11-19 11:35 UTC, legalsylvain commented
/ocabot merge

2019-11-19 12:27 UTC, merged